apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-prod
  namespace: helloworld-prod
  labels:
    name: helloworld-prod
spec:
  project: default
  source:
    repoURL: 'https://github.com/alekseydemidov/testargo-cd/'
    path: helm
    targetRevision: prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: helloworld-prod
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
